FROM perception-base:latest

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workspace/Autonomous-Driving-Perception-System
COPY . .

RUN python3 -m venv /opt/sam_venv && \
    /opt/sam_venv/bin/pip install --upgrade pip

# 后续按项目真实依赖补充
# 例如：
# RUN /opt/sam_venv/bin/pip install -r src/sam2_ros/requirements.txt

RUN apt-get update && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -r -y || true

RUN source /opt/ros/jazzy/setup.bash && \
    colcon build --merge-install || true

CMD ["bash", "-c", "source /opt/ros/jazzy/setup.bash && \
    source install/setup.bash && \
    export PATH=/opt/sam_venv/bin:$PATH && \
    export PYTHONPATH=/opt/sam_venv/lib/python3.12/site-packages:$PYTHONPATH && \
    export PYTHONPATH=/workspace/Autonomous-Driving-Perception-System:$PYTHONPATH && \
    ros2 launch sam2_ros sam2_ros.launch.py"]
