FROM ros:jazzy-ros-base-noble

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN apt-get update && apt-get install -y \
    locales \
    curl \
    wget \
    git \
    nano \
    vim \
    bash \
    sudo \
    gnupg2 \
    lsb-release \
    software-properties-common \
    build-essential \
    cmake \
    python3-pip \
    python3-venv \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-vcstool \
 && locale-gen en_US.UTF-8 \
 && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true
RUN rosdep update || true

WORKDIR /workspace/Autonomous-Driving-Perception-System

CMD ["/bin/bash"]
